import java.util.Scanner;
import java.util.Arrays;
public class Anagram{
	public static void main(String[] args){
		Scanner sc=new Scanner(System.in);
		System.out.println("Anagram of Words");
		System.out.print("Enter no. of words to store in array: ");
		int n=sc.nextInt();
		String[] arr=new String[n];
		System.out.println("Enter words at all indices of Array: ");
		for(int i=0;i<n;i++){
			System.out.print("arr["+i+"]: ");
			arr[i]=sc.next();
		}
		int index=(int)(Math.random()*n);
		System.out.print("Array of String: ");
		for(int i=0;i<n;i++){
			System.out.print(arr[i]+" ");
		}
		System.out.println("\nGenerated by random: arr["+index+"]: "+arr[index]);
		System.out.print("Enter any word: ");
		String s=sc.next();
		if(s.length()!=arr[index].length()){
			System.out.println("Not an Anagram");
			return;
		}
		char[] original_word=arr[index].toCharArray();
		char[] new_word=s.toCharArray();
		Arrays.sort(original_word);
		Arrays.sort(new_word);
		for(int i=0;i<s.length();i++){
			if(original_word[i]!=new_word[i]){
				System.out.println("Not an Anagram");
				return;
			}
		}
		System.out.println("Anagram");
		
	}
}